import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { useWizard } from "../../state/wizard";
export default function CalcMenu() {
    const nav = useNavigate();
    const { unlocks } = useWizard();
    const Item = ({ title, desc, to, enabled, }) => (_jsxs("button", { type: "button", onClick: () => enabled && nav(to), className: `rounded-xl border p-5 text-left shadow hover:shadow-md ${enabled ? "bg-white" : "bg-slate-100 opacity-60 cursor-not-allowed"}`, children: [_jsx("div", { className: "text-lg font-semibold mb-1", children: title }), _jsx("div", { className: "text-slate-600 text-sm", children: desc })] }));
    return (_jsxs("div", { className: "grid gap-4", children: [_jsx("h2", { className: "text-xl font-semibold", children: "Berechnungen \u2013 Untermen\u00FC" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsx(Item, { title: "Kundendaten", desc: "Grunddaten erfassen", to: "/calc/customer", enabled: true }), _jsx(Item, { title: "Bedarfsanalyse", desc: "Verbr\u00E4uche, Tarife", to: "/calc/needs", enabled: unlocks.hasCustomerData }), _jsx(Item, { title: "Geb\u00E4udedaten", desc: "Dachdaten, Ausrichtung", to: "/calc/building", enabled: unlocks.hasCustomerData }), _jsx(Item, { title: "Zus\u00E4tzliche Angaben", desc: "Interessen & Finanzierung", to: "/calc/options", enabled: unlocks.hasCustomerData }), _jsx(Item, { title: "Solar Calculator", desc: "Technik & kWp", to: "/calc/solar", enabled: unlocks.hasNeedsAnalysis && unlocks.pvEnabled }), _jsx(Item, { title: "W\u00E4rmepumpe Simulator", desc: "Heizlast & Empfehlung", to: "/calc/heatpump", enabled: unlocks.hasNeedsAnalysis && unlocks.hpEnabled }), _jsx(Item, { title: "Ergebnisse", desc: "Kennzahlen & KPIs", to: "/results", enabled: unlocks.hasNeedsAnalysis }), _jsx(Item, { title: "Dashboard", desc: "Charts & Visualisierungen", to: "/dashboard", enabled: unlocks.hasNeedsAnalysis }), _jsx(Item, { title: "Dokumentenerstellung", desc: "Standard / erweitert / Multi-PDF", to: "/documents", enabled: unlocks.hasNeedsAnalysis })] })] }));
}
