import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from 'primereact/card';
import { Panel } from 'primereact/panel';
import { Button } from 'primereact/button';
import { Divider } from 'primereact/divider';
export default function Documents() {
    const header = (_jsxs("div", { className: "flex align-items-center gap-2", children: [_jsx("i", { className: "pi pi-file-text" }), _jsx("span", { children: "Dokumentenerstellung" })] }));
    return (_jsx(Card, { title: header, className: "m-3", pt: {
            body: { className: 'p-4' },
            content: { className: 'p-0' }
        }, children: _jsxs("div", { className: "space-y-4", children: [_jsx("p", { className: "text-700 mb-4", children: "Standard / erweitert / Multi-PDF, Vorlagen & Optionen." }), _jsx(Divider, {}), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx(Panel, { header: "Standard PDF", className: "w-full", children: _jsxs("div", { className: "flex flex-column gap-3", children: [_jsxs("div", { className: "flex align-items-center gap-2 text-600", children: [_jsx("i", { className: "pi pi-check" }), _jsx("span", { children: "Grundlegendes Angebot" })] }), _jsx(Button, { label: "Erstellen", icon: "pi pi-file-pdf", className: "p-button-outlined", size: "small" })] }) }), _jsx(Panel, { header: "Erweiterte PDF", className: "w-full", children: _jsxs("div", { className: "flex flex-column gap-3", children: [_jsxs("div", { className: "flex align-items-center gap-2 text-600", children: [_jsx("i", { className: "pi pi-file" }), _jsx("span", { children: "Detaillierte Analyse" })] }), _jsx(Button, { label: "Erstellen", icon: "pi pi-file-pdf", className: "p-button-outlined", size: "small" })] }) }), _jsx(Panel, { header: "Multi-PDF", className: "w-full", children: _jsxs("div", { className: "flex flex-column gap-3", children: [_jsxs("div", { className: "flex align-items-center gap-2 text-600", children: [_jsx("i", { className: "pi pi-download" }), _jsx("span", { children: "Mehrere Dokumente" })] }), _jsx(Button, { label: "Konfigurieren", icon: "pi pi-cog", className: "p-button-outlined", size: "small" })] }) })] }), _jsx(Divider, {}), _jsx(Panel, { header: "Vorlagen & Optionen", className: "w-full", children: _jsxs("div", { className: "flex justify-content-between align-items-center", children: [_jsxs("div", { className: "flex align-items-center gap-2 text-600", children: [_jsx("i", { className: "pi pi-cog" }), _jsx("span", { children: "PDF-Vorlagen verwalten und Optionen anpassen" })] }), _jsx(Button, { label: "Einstellungen", icon: "pi pi-cog", className: "p-button-text", size: "small" })] }) })] }) }));
}
