import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Routes, Route, Link, useLocation } from 'react-router-dom';
// Navigationskomponente für PDF-Seiten
function PdfNavigation() {
    const location = useLocation();
    return (_jsx("div", { className: "bg-white border-b border-slate-200 mb-6", children: _jsxs("div", { className: "flex flex-wrap gap-2 p-4", children: [_jsx(Link, { to: "/pdf", className: `px-4 py-2 rounded-lg transition-colors ${location.pathname === '/pdf'
                        ? 'bg-blue-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`, children: "\uD83D\uDCC4 PDF-Hub" }), _jsx(Link, { to: "/pdf/standard", className: `px-4 py-2 rounded-lg transition-colors ${location.pathname === '/pdf/standard'
                        ? 'bg-blue-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`, children: "\uD83D\uDCD1 Standard" }), _jsx(Link, { to: "/pdf/extended", className: `px-4 py-2 rounded-lg transition-colors ${location.pathname === '/pdf/extended'
                        ? 'bg-blue-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`, children: "\uD83D\uDCCB Erweitert" }), _jsx(Link, { to: "/pdf/multi", className: `px-4 py-2 rounded-lg transition-colors ${location.pathname === '/pdf/multi'
                        ? 'bg-blue-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`, children: "\uD83D\uDCDA Multi-PDF" }), _jsx(Link, { to: "/pdf/preview", className: `px-4 py-2 rounded-lg transition-colors ${location.pathname === '/pdf/preview'
                        ? 'bg-blue-600 text-white'
                        : 'bg-slate-100 text-slate-700 hover:bg-slate-200'}`, children: "\uD83D\uDC41\uFE0F Vorschau" }), _jsx(Link, { to: "/", className: "ml-auto px-4 py-2 rounded-lg bg-gray-500 text-white hover:bg-gray-600 transition-colors", children: "\u2190 Startseite" })] }) }));
}
function PdfStandard() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(PdfNavigation, {}), _jsx("div", { className: "max-w-4xl mx-auto p-6", children: _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: "Standard-PDF (7 Seiten)" }), _jsx("p", { className: "text-slate-600 mb-6", children: "Klassisches Angebot mit PV-Templates (nt_nt_01 bis nt_nt_07) oder WP-Templates (hp_nt_01 bis hp_nt_07)." }), _jsxs("div", { className: "space-y-3", children: [_jsx("button", { className: "block w-full rounded border bg-white p-3 text-left hover:bg-slate-50 border-slate-200 shadow-sm", children: "\uD83D\uDCD1 PV-Standard-PDF generieren" }), _jsx("button", { className: "block w-full rounded border bg-white p-3 text-left hover:bg-slate-50 border-slate-200 shadow-sm", children: "\uD83D\uDD25 WP-Standard-PDF generieren" }), _jsx("button", { className: "block w-full rounded border bg-white p-3 text-left hover:bg-slate-50 border-slate-200 shadow-sm", children: "\u26A1 Kombiniertes PV+WP-PDF generieren" })] })] }) })] }));
}
function PdfExtended() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(PdfNavigation, {}), _jsx("div", { className: "max-w-4xl mx-auto p-6", children: _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: "Erweiterte PDF-Ausgabe" }), _jsx("p", { className: "text-slate-600 mb-6", children: "Standard-PDF plus zus\u00E4tzliche Optionen wie Datenbl\u00E4tter, Diagramme, Firmen-Dokumente und AGB." }), _jsxs("div", { className: "grid gap-3 md:grid-cols-2 mb-6", children: [_jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", className: "rounded border-slate-300" }), _jsx("span", { children: "\uD83D\uDCCB Produkt-Datenbl\u00E4tter" })] }), _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", className: "rounded border-slate-300" }), _jsx("span", { children: "\uD83D\uDCCA Wirtschaftlichkeits-Diagramme" })] }), _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", className: "rounded border-slate-300" }), _jsx("span", { children: "\uD83C\uDFE2 Firmen-Logos & Zertifikate" })] }), _jsxs("label", { className: "flex items-center space-x-2", children: [_jsx("input", { type: "checkbox", className: "rounded border-slate-300" }), _jsx("span", { children: "\uD83D\uDCDC AGB & Vertragskonditionen" })] })] }), _jsx("button", { className: "w-full rounded bg-blue-600 px-4 py-3 text-white hover:bg-blue-700 transition-colors", children: "\uD83D\uDCC4 Erweiterte PDF generieren" })] }) })] }));
}
function PdfMulti() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(PdfNavigation, {}), _jsx("div", { className: "max-w-4xl mx-auto p-6", children: _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: "Multi-PDF Generation" }), _jsx("p", { className: "text-slate-600 mb-6", children: "Erstellt mehrere Angebote verschiedener Firmen mit unterschiedlichen Preisen und Brandings als ZIP-Download." }), _jsxs("div", { className: "space-y-4 mb-6", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Anzahl Firmen" }), _jsxs("select", { className: "w-full rounded border border-slate-300 px-3 py-2", children: [_jsx("option", { children: "2 Firmen" }), _jsx("option", { children: "3 Firmen" }), _jsx("option", { children: "5 Firmen" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Preis-Staffelung" }), _jsxs("select", { className: "w-full rounded border border-slate-300 px-3 py-2", children: [_jsx("option", { children: "Linear (-5%, -10%, -15%)" }), _jsx("option", { children: "Zuf\u00E4llig (\u00B15-15%)" }), _jsx("option", { children: "Kategoriespezifisch" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium mb-2", children: "Rotation" }), _jsxs("select", { className: "w-full rounded border border-slate-300 px-3 py-2", children: [_jsx("option", { children: "Linear" }), _jsx("option", { children: "Zuf\u00E4llig" }), _jsx("option", { children: "Nach Firmengr\u00F6\u00DFe" })] })] })] }), _jsx("button", { className: "w-full rounded bg-purple-600 px-4 py-3 text-white hover:bg-purple-700 transition-colors", children: "\uD83D\uDCDA Multi-PDF erstellen (ZIP-Download)" })] }) })] }));
}
function PdfPreview() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(PdfNavigation, {}), _jsx("div", { className: "max-w-4xl mx-auto p-6", children: _jsxs("div", { className: "bg-white rounded-lg shadow p-6", children: [_jsx("h3", { className: "text-lg font-semibold mb-4", children: "PDF-Vorschau" }), _jsx("p", { className: "text-slate-600 mb-6", children: "Schnellvorschau, vollst\u00E4ndige Vorschau oder seitenweise Ansicht mit Zoom und Debug-Overlay." }), _jsxs("div", { className: "grid gap-3 md:grid-cols-3 mb-6", children: [_jsx("button", { className: "rounded border border-slate-300 bg-white p-3 hover:bg-slate-50 transition-colors", children: "\u26A1 Schnellvorschau (3 Sek.)" }), _jsx("button", { className: "rounded border border-slate-300 bg-white p-3 hover:bg-slate-50 transition-colors", children: "\uD83D\uDCCB Vollst\u00E4ndige Vorschau" }), _jsx("button", { className: "rounded border border-slate-300 bg-white p-3 hover:bg-slate-50 transition-colors", children: "\uD83D\uDCC4 Seitenweise durchbl\u00E4ttern" })] }), _jsx("div", { className: "mt-4 border rounded p-8 bg-slate-50 border-slate-300", children: _jsx("div", { className: "text-center text-slate-500", children: "\uD83D\uDCC4 PDF-Vorschau wird hier angezeigt" }) })] }) })] }));
}
function PdfHubMain() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(PdfNavigation, {}), _jsxs("div", { className: "max-w-6xl mx-auto p-6", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h2", { className: "text-3xl font-bold text-slate-800 mb-4", children: "\uD83D\uDCC4 PDF-Generator Hub" }), _jsx("p", { className: "text-slate-600 max-w-2xl mx-auto", children: "Erstellen Sie professionelle PV-Angebote in verschiedenen Varianten. Von Standard-PDFs bis hin zu erweiterten Multi-Angeboten." })] }), _jsxs("div", { className: "grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: [_jsxs(Link, { to: "/pdf/standard", className: "block rounded-lg border bg-white p-6 shadow hover:shadow-md transition-shadow border-slate-200", children: [_jsx("div", { className: "text-4xl mb-4 text-center", children: "\uD83D\uDCD1" }), _jsx("h3", { className: "text-lg font-semibold mb-2 text-center", children: "Standard-PDF" }), _jsx("p", { className: "text-sm text-slate-600 text-center", children: "Klassische 7-seitige Angebote f\u00FCr PV oder W\u00E4rmepumpen" })] }), _jsxs(Link, { to: "/pdf/extended", className: "block rounded-lg border bg-white p-6 shadow hover:shadow-md transition-shadow border-slate-200", children: [_jsx("div", { className: "text-4xl mb-4 text-center", children: "\uD83D\uDCCB" }), _jsx("h3", { className: "text-lg font-semibold mb-2 text-center", children: "Erweiterte PDF" }), _jsx("p", { className: "text-sm text-slate-600 text-center", children: "Standard + Datenbl\u00E4tter, Diagramme und Zusatzdokumente" })] }), _jsxs(Link, { to: "/pdf/multi", className: "block rounded-lg border bg-white p-6 shadow hover:shadow-md transition-shadow border-slate-200", children: [_jsx("div", { className: "text-4xl mb-4 text-center", children: "\uD83D\uDCDA" }), _jsx("h3", { className: "text-lg font-semibold mb-2 text-center", children: "Multi-PDF" }), _jsx("p", { className: "text-sm text-slate-600 text-center", children: "Mehrere Angebote verschiedener Firmen als ZIP-Download" })] }), _jsxs(Link, { to: "/pdf/preview", className: "block rounded-lg border bg-white p-6 shadow hover:shadow-md transition-shadow border-slate-200", children: [_jsx("div", { className: "text-4xl mb-4 text-center", children: "\uD83D\uDC41\uFE0F" }), _jsx("h3", { className: "text-lg font-semibold mb-2 text-center", children: "Vorschau" }), _jsx("p", { className: "text-sm text-slate-600 text-center", children: "PDF-Vorschau mit Zoom und Debug-Funktionen" })] })] })] })] }));
}
export default function PdfHub() {
    return (_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(PdfHubMain, {}) }), _jsx(Route, { path: "/standard", element: _jsx(PdfStandard, {}) }), _jsx(Route, { path: "/extended", element: _jsx(PdfExtended, {}) }), _jsx(Route, { path: "/multi", element: _jsx(PdfMulti, {}) }), _jsx(Route, { path: "/preview", element: _jsx(PdfPreview, {}) })] }));
}
